config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories
  resources :products
  resources :route_conditions

  resource :destination_resolvers, only: %i[new create]

  root 'destination_resolvers#new'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true

  has_many :products
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :reference, presence: true, length: { maximum: 20 }
  validates :name, presence: true
  validates :price, presence: true
  validates :category, presence: true

  belongs_to :category

  after_destroy do
    # TODO: Make sure to remove the product from every route condition as well
  end
end

app/models/route_condition.rb
# frozen_string_literal: true

class RouteCondition < ApplicationRecord
  validates :destination, presence: true
  validates :max_price, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.order(:name).all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/destination_resolvers_controller.rb
# frozen_string_literal: true

class DestinationResolversController < ApplicationController
  def new; end

  def create
    @product = Product.find_by(reference: params[:reference])
    @destination = DestinationResolver.new.perform(product: @product)

    # TODO: error handling for product not found
    # TODO: error handling when no destination could be found
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :set_categories

  # GET /products
  # GET /products.json
  def index
    @products = Product.includes(:category).order(:name).all
  end

  # GET /products/1
  # GET /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:reference, :name, :price, :category_id)
  end

  def set_categories
    @categories = Category.order(:name).all
  end
end

app/controllers/route_conditions_controller.rb
# frozen_string_literal: true

class RouteConditionsController < ApplicationController
  before_action :set_route_condition, only: %i[show edit update destroy]

  # GET /route_conditions
  # GET /route_conditions.json
  def index
    @route_conditions = RouteCondition.all
  end

  # GET /route_conditions/1
  # GET /route_conditions/1.json
  def show; end

  # GET /route_conditions/new
  def new
    @route_condition = RouteCondition.new
  end

  # GET /route_conditions/1/edit
  def edit; end

  # POST /route_conditions
  # POST /route_conditions.json
  def create
    @route_condition = RouteCondition.new(route_condition_params)

    respond_to do |format|
      if @route_condition.save
        format.html { redirect_to @route_condition, notice: 'Route condition was successfully created.' }
        format.json { render :show, status: :created, location: @route_condition }
      else
        format.html { render :new }
        format.json { render json: @route_condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /route_conditions/1
  # PATCH/PUT /route_conditions/1.json
  def update
    respond_to do |format|
      if @route_condition.update(route_condition_params)
        format.html { redirect_to @route_condition, notice: 'Route condition was successfully updated.' }
        format.json { render :show, status: :ok, location: @route_condition }
      else
        format.html { render :edit }
        format.json { render json: @route_condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /route_conditions/1
  # DELETE /route_conditions/1.json
  def destroy
    @route_condition.destroy
    respond_to do |format|
      format.html { redirect_to route_conditions_url, notice: 'Route condition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_route_condition
    @route_condition = RouteCondition.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def route_condition_params
    params.require(:route_condition).permit!
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= turbo_frame_tag "category" do %>
  <%= render 'form', category: @category %>
<% end %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= turbo_frame_tag "category" do %>
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

<% end %>

<div id="products">
  <%= render @category.products %>
</div>

app/views/destination_resolvers/create.html.erb
<h1>Destination</h1>

The destination for <%= @product.name %> is <%= @destination %>

app/views/destination_resolvers/new.html.erb
<h1>Resolve destination for product</h1>

<%= form_with url: destination_resolvers_path do |form| %>

  <div class="field">
    <%= form.label :reference %>
    <%= form.text_field :reference %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Warehouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul id="mainmenu">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Categories', categories_path %></li>
        <li><%= link_to 'Products', products_path %></li>
        <li><%= link_to 'Route conditions', route_conditions_path %></li>
      </ul>
    </header>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :reference %>
    <%= form.text_field :reference %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<p id=<%= dom_id product %>>
  <%= product.name %>
</p>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Reference</th>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.reference %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.category.name %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= turbo_frame_tag "product" do %>
  <p>
    <strong>Reference:</strong>
    <%= @product.reference %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @product.price %>
  </p>

  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back', products_path %>
<% end %>

app/views/route_conditions/_form.html.erb
<%= form_with(model: route_condition) do |form| %>
  <% if route_condition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(route_condition.errors.count, "error") %> prohibited this route_condition from being saved:</h2>

      <ul>
        <% route_condition.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_ids %>
    <%= form.collection_check_boxes :product_ids, Product.all, :id, :reference %>
  </div>
  <hr>
  <div class="field">
    <%= form.label :category_ids %>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name %>
  </div>
  <hr>
  <div class="field">
    <%= form.label :max_price %>
    <%= form.number_field :max_price %>
  </div>
  <hr>
  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/route_conditions/edit.html.erb
<h1>Editing Route Condition</h1>

<%= render 'form', route_condition: @route_condition %>

<%= link_to 'Show', @route_condition %> |
<%= link_to 'Back', route_conditions_path %>

app/views/route_conditions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Route Conditions</h1>

<table>
  <thead>
    <tr>
      <th>Destination</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @route_conditions.each do |route_condition| %>
      <tr>
        <td><%= route_condition.destination %></td>
        <td><%= link_to 'Show', route_condition %></td>
        <td><%= link_to 'Edit', edit_route_condition_path(route_condition) %></td>
        <td><%= link_to 'Destroy', route_condition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route Condition', new_route_condition_path %>

app/views/route_conditions/new.html.erb
<h1>New Route Condition</h1>

<%= render 'form', route_condition: @route_condition %>

<%= link_to 'Back', route_conditions_path %>

app/views/route_conditions/show.html.erb
<p id="notice"><%= notice %></p>

<%= @route_condition.destination %>

<%= link_to 'Edit', edit_route_condition_path(@route_condition) %> |
<%= link_to 'Back', route_conditions_path %>